### ISSUE TITLE
Missing parantheses

### ISSUE THREAD

**Issue by yani1shu** [dlcowen/FSEventsParser#1]
When i try to run i get the following error:

C:\Users\yschiff\Downloads\FSEventsParser-master>FSEParser_v2.0.py -h
  File "C:\Users\yschiff\Downloads\FSEventsParser-master\FSEParser_v2.0.py", line 75
    print '\n=========================================================================='
                                                                                       ^
SyntaxError: Missing parentheses in call to 'print'

```
                                                                                   ^
```

**Comment by gc-nibrahim** [comment]
Hello,
The syntax error "Missing parentheses in call to 'print'" is because the FSEvents parser script was written using Python 2 syntax. If you're running Python 3, you will receive this error.

http://stackoverflow.com/questions/25445439/what-does-syntaxerror-missing-parentheses-in-call-to-print-mean-in-python

The easiest solution to overcome this error may be to uninstall Python 3.x and install Python 2.7. Alternately, you may be able to install both versions side by side. See the link below for one implementation (though I've never tried it).

http://stackoverflow.com/questions/341184/can-i-install-python-3-x-and-2-x-on-the-same-computer

Let me know if that helps.

**Comment by yani1shu** [comment]
Thanks, that fixed it.
