### ISSUE TITLE
Apparent Event Flag conflict with Apple source documents

### ISSUE THREAD

**Issue by slo-sleuth** [dlcowen/FSEventsParser#2]
There seems to be a difference between your interpretation of the event flags and the Apple reference on the topic (https://developer.apple.com/library/mac/documentation/Darwin/Reference/FSEvents_Ref/#//apple_ref/doc/constant_group/FSEventStreamEventFlags).  

For example, Apple shows the following:

```
enum {
   kFSEventStreamEventFlagNone = 0x00000000,
   kFSEventStreamEventFlagMustScanSubDirs = 0x00000001,
   kFSEventStreamEventFlagUserDropped = 0x00000002,
   kFSEventStreamEventFlagKernelDropped = 0x00000004,
   kFSEventStreamEventFlagEventIdsWrapped = 0x00000008,
   kFSEventStreamEventFlagHistoryDone = 0x00000010,
   kFSEventStreamEventFlagRootChanged = 0x00000020,
   kFSEventStreamEventFlagMount = 0x00000040,
   kFSEventStreamEventFlagUnmount = 0x00000080 , /* These flags are only set if you specified the FileEvents */
   /* flags when creating the stream.*/
   kFSEventStreamEventFlagItemCreated = 0x00000100,
   kFSEventStreamEventFlagItemRemoved = 0x00000200,
   kFSEventStreamEventFlagItemInodeMetaMod = 0x00000400,
   kFSEventStreamEventFlagItemRenamed = 0x00000800,
   kFSEventStreamEventFlagItemModified = 0x00001000,
   kFSEventStreamEventFlagItemFinderInfoMod = 0x00002000,
   kFSEventStreamEventFlagItemChangeOwner = 0x00004000,
   kFSEventStreamEventFlagItemXattrMod = 0x00008000,
   kFSEventStreamEventFlagItemIsFile = 0x00010000,
   kFSEventStreamEventFlagItemIsDir = 0x00020000,
   kFSEventStreamEventFlagItemIsSymlink = 0x00040000 
};
```

Your EVENTMASK dictionary defines the flags differently:

```
EVENTMASK = {
    0x00000000: 'None;',
    0x00000001: 'FolderEvent;',
    0x00000002: 'Mount;',
    0x00000004: 'Unmount;',
    0x00000020: 'EndOfTransaction;',
    0x00000800: 'LastHardLinkRemoved;',
    0x00001000: 'HardLink;',
    0x00004000: 'SymbolicLink;',
    0x00008000: 'FileEvent;',
    0x00010000: 'PermissionChange;',
    0x00020000: 'ExtendedAttrModified;',
    0x00040000: 'ExtendedAttrRemoved;',
    0x00100000: 'DocumentRevisioning;',
    0x01000000: 'Created;',
    0x02000000: 'Removed;',
    0x04000000: 'InodeMetaMod;',
    0x08000000: 'Renamed;',
    0x10000000: 'Modified;',
    0x20000000: 'Exchange;',
    0x40000000: 'FinderInfoMod;',
    0x80000000: 'FolderCreated;',
}
```

How do you reconcile this or what is your source for the values in the EVENTMASK dictionary?

Thanks.

**Comment by gc-nibrahim** [comment]
Hi slo-slueth.

Thank you for your feedback. 

The Apple documentation referenced has since been removed but I am familiar with it as a result of my research. I have found this information which appears to be an updated version and includes additional flags that the original Apple documentation did not include. https://developer.apple.com/reference/coreservices/1455361-fseventstreameventflags?language=objc

With regards to reconciling the event flags. Apple's documentation of the FSEvents API is in reference to live event streaming, subscribers, and callbacks. These events are stored to memory as buffers. When the buffer reaches its max size, it is written to disk. Subscribing to events allows an application to see events in real-time, only a small portion of the public API references historical events or as they call it "persistent events", which I assume Apple means events stored to disk. 
Persistent events are referenced in https://developer.apple.com/library/content/documentation/Darwin/Conceptual/FSEvents_ProgGuide/UsingtheFSEventsFramework/UsingtheFSEventsFramework.html#//apple_ref/doc/uid/TP40005289-CH4-SW10

I have not found any documentation referencing how FSEvents are stored to disk nor any information related to how the event flags are interpreted or stored within an FSEvent log.

However, my source for the EVENTMASK dictionary is through research and testing. In addition, the flags have been confirmed by two independently working research parties.

I hope this helps. Let me know if you have any further questions.

All the best,
gc-nibrahim
